# syntax=docker/dockerfile:1.7

# tokenusage Dockerfile — multi-stage build that yields a small runtime image
# with Next.js standalone output and the better-sqlite3 native binding.

# ---------- Stage 1: dependencies ----------
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat python3 make g++
WORKDIR /app

# pnpm via corepack — pinned to whatever the lockfile expects.
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
# `prebuild-install` will fetch a prebuilt better-sqlite3 binary when one
# matches; otherwise node-gyp falls back to compiling here.
RUN pnpm install --frozen-lockfile --prod=false


# ---------- Stage 2: build ----------
FROM node:22-alpine AS builder
WORKDIR /app
RUN corepack enable
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm build


# ---------- Stage 3: runtime ----------
FROM node:22-alpine AS runner
WORKDIR /app

ARG TOKENUSAGE_GIT_SHA=unknown
ENV NODE_ENV=production
ENV TOKENUSAGE_GIT_SHA=$TOKENUSAGE_GIT_SHA
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
# Mountable volume for the server DB and any user price overrides.
ENV TOKENUSAGE_SERVER_DB=/data/server.db

RUN addgroup -S --gid 1001 nodejs && adduser -S --uid 1001 nextjs && \
    mkdir /data && chown nextjs:nodejs /data

# Standalone output already includes a minimal node_modules tree.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/data/prices.default.json ./data/prices.default.json
COPY --from=builder --chown=nextjs:nodejs /app/data/sample.db ./data/sample.db
# Standalone build doesn't include the Next.js runtime binary; the entrypoint
# is server.js generated by Next.
COPY --from=builder --chown=nextjs:nodejs /app/agent ./agent

USER nextjs

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:3000/api/health || exit 1

VOLUME ["/data"]
CMD ["node", "server.js"]
